version: '3.5'
services:
  fx-postgres:
    image: postgres:10.2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    command: postgres -c 'shared_buffers=256MB' -c 'max_connections=300'
    volumes:
      - /fx-security-enterprise/postgres/data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

    # create db, user, pass

  fx-elasticsearch:
    image: elasticsearch:5
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
    environment:
      - ES_JAVA_OPTS=${ELASTICSEARCH_MEM}
    volumes:
      - /fx-security-enterprise/elasticsearch/data:/usr/share/elasticsearch/data
    configs:
      - source: elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

  fx-rabbitmq:
    image: rabbitmq:3.7-management
    hostname: fx_rabbitmq_stg
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]
    environment:
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_DEFAULT_VHOST=${RABBITMQ_DEFAULT_VHOST}
      - RABBITMQ_VM_MEMORY_HIGH_WATERMARK=${RABBITMQ_VM_MEMORY_HIGH_WATERMARK}
    volumes:
      - /fx-security-enterprise/rabbitmq/data:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 5671:5671
      - 15672:15762
      - 15671:15671
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

    # create vhost, user-cp,
    # TODO user-mail, user-sync, user-bot

#volumes:
#  pgdata:
#  esdata:
#  mqdata:
configs:
  elasticsearch.yml:
    external: true

